# Class UATHamburgerMenu
## Index### Constructors* [constructor](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#constructor)### Properties* [_cocoInit](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#_cocoinit)* [applyHostClass](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#applyhostclass)* [closeOnClickOutside](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#closeonclickoutside)* [expandOnQuery](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#expandonquery)* [items](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#items)* [panel](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#panel)* [previousExpansion](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#previousexpansion)* [rightItems](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#rightitems)* [showOnHover](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#showonhover)* [toggleOnClick](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#toggleonclick)### Accessors* [expanded](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#expanded)* [isOpen](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#isopen)* [itemElementRefs](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#itemelementrefs)### Methods* [ngOnInit](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#ngoninit)* [onWindowResize](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html#onwindowresize)## Constructors### new UATHamburgerMenu(): [UATHamburgerMenu](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html)  * Defined in [hamburger-menu/hamburger-menu.component.ts:57](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L57)#### Returns: [UATHamburgerMenu](_hamburger_menu_hamburger_menu_component_.uathamburgermenu.html)## Properties### Private _cocoInit: boolean
* Defined in [hamburger-menu/hamburger-menu.component.ts:51](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L51)### applyHostClass: boolean
* Defined in [hamburger-menu/hamburger-menu.component.ts:28](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L28)### closeOnClickOutside: boolean
* Defined in [hamburger-menu/hamburger-menu.component.ts:47](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L47)### expandOnQuery: string
* Defined in [hamburger-menu/hamburger-menu.component.ts:43](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L43)### items: QueryList<ElementRef>
* Defined in [hamburger-menu/hamburger-menu.component.ts:32](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L32)### panel: [UATSlidingPanel](_sliding_panel_sliding_panel_component_.uatslidingpanel.html)
* Defined in [hamburger-menu/hamburger-menu.component.ts:30](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L30)### Private previousExpansion: boolean
* Defined in [hamburger-menu/hamburger-menu.component.ts:57](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L57)### rightItems: QueryList<ElementRef>
	* Defined in [hamburger-menu/hamburger-menu.component.ts:33](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L33)### showOnHover: boolean
	* Defined in [hamburger-menu/hamburger-menu.component.ts:45](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L45)### toggleOnClick: boolean
	* Defined in [hamburger-menu/hamburger-menu.component.ts:49](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L49)## Accessors### expanded* get (): boolean  * Defined in [hamburger-menu/hamburger-menu.component.ts:53](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L53)#### Returns: boolean### isOpen* get (): boolean  * Defined in [hamburger-menu/hamburger-menu.component.ts:39](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L39)#### Returns: boolean### itemElementRefs* get (): ElementRef[]  * Defined in [hamburger-menu/hamburger-menu.component.ts:35](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L35)#### Returns: ElementRef[]## Methods### ngOnInit(): void  * Defined in [hamburger-menu/hamburger-menu.component.ts:62](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L62)#### Returns: void### onWindowResize(): voidEvaluate the media query on window resizing.  * Defined in [hamburger-menu/hamburger-menu.component.ts:75](https://github.com/tme321/Unopinionated-Angular/blob/16a724b/src/lib/hamburger-menu/hamburger-menu.component.ts#L75)#### Returns: void
	Generated using [TypeDoc](http://typedoc.io)